# Generated by Django 4.1.3 on 2022-11-23 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_header',
            field=models.CharField(max_length=90),
        ),
    ]
